default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release --flavor Production -t lib/main_production.dart --no-tree-shake-icons"
      firebase_app_distribution(
        app: "1:45066686417:android:b2dbb8ddebc0fbf2075af0",
        firebase_cli_token: "1//039a_GCM_nkEfCgYIARAAGAMSNwF-L9Irmjw-rbyH3wx3sOTR1_-pHsFpGxZB7NcwXLMLSbffOSv5OG_yaZkR8xrmSjZW4Zd78bo",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "tareqkhalid092@gmail.com",
        release_notes: "First Fastlane Firebase App Distribution✅",
        )
  end
end
