name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4.1"  # Ensure correct Ruby version
        bundler-cache: false    # Disable auto-caching for now

    - name: Fix Gemfile.lock Platform Issue
      run: |
        bundle lock --add-platform x86_64-linux
      working-directory: android

    - name: Install Bundler and Dependencies
      run: |
        gem install bundler:2.5.22
        bundle install --jobs 4
      working-directory: android

    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        fastlane android firebase_distribution
      working-directory: android
